In [11]:
import numpy as np
from numpy.linalg import norm
 
# define two lists or array
A = np.array([[-0.8,0.6,0],[0,0,-1],[0.6,0.8,0]])
B = np.array([[1,0,0],[0,0,1],[0,1,0]])
 
print("A:", A)
print("B:", B)
 
# compute cosine similarity
cosine = np.dot(A,B)

A: [[-0.8  0.6  0. ]
 [ 0.   0.  -1. ]
 [ 0.6  0.8  0. ]]
B: [[1 0 0]
 [0 0 1]
 [0 1 0]]


In [12]:
cosine

array([[-0.8,  0. ,  0.6],
       [ 0. , -1. ,  0. ],
       [ 0.6,  0. ,  0.8]])